import type { User, BrokerProfile, LenderProfile } from '../types/user';
import type { Loan } from '../types/loan';
import type { LoanDocument, LoanCondition } from '../types/document';
import type { AuditLogEntry, Message } from '../types/pipeline';

// Mock Users
export const mockBrokerUser: User = {
  id: 'broker-1',
  email: 'broker@example.com',
  role: 'broker',
  firstName: 'John',
  lastName: 'Smith',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
};

export const mockLenderUser: User = {
  id: 'lender-1',
  email: 'lender@example.com',
  role: 'lender',
  firstName: 'Sarah',
  lastName: 'Johnson',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
};

export const mockBrokerProfile: BrokerProfile = {
  id: 'broker-profile-1',
  userId: 'broker-1',
  companyName: 'Premier Mortgage Group',
  nmls: '123456',
  phone: '555-0123',
  address: '123 Main St',
  city: 'San Francisco',
  state: 'CA',
  zipCode: '94102',
  status: 'approved',
  approvedAt: '2024-01-15T00:00:00Z',
  approvedBy: 'lender-1',
};

export const mockLenderProfile: LenderProfile = {
  id: 'lender-profile-1',
  userId: 'lender-1',
  companyName: 'National Lending Corp',
  department: 'Underwriting',
  phone: '555-0456',
  permissions: ['view_all_loans', 'approve_loans', 'manage_brokers'],
};

// Mock Loans
export const mockLoans: Loan[] = [
  {
    id: 'loan-1',
    brokerId: 'broker-1',
    brokerName: 'Premier Mortgage Group',
    borrower: {
      firstName: 'Michael',
      lastName: 'Anderson',
      email: 'michael.anderson@email.com',
      phone: '555-1234',
      dateOfBirth: '1985-03-15',
      creditScore: 720,
      employerName: 'Tech Solutions Inc',
      jobTitle: 'Senior Engineer',
      yearsEmployed: 5,
      isSelfEmployed: false,
      annualIncome: 125000,
    },
    property: {
      address: '456 Oak Avenue',
      city: 'San Jose',
      state: 'CA',
      zipCode: '95123',
      county: 'Santa Clara',
      propertyType: 'sfr',
      occupancy: 'primary',
      propertyValue: 850000,
      yearBuilt: 2015,
      units: 1,
    },
    loanDetails: {
      purpose: 'purchase',
      loanAmount: 680000,
      loanTerm: 30,
      amortization: 30,
      interestRate: 6.75,
      paymentType: 'fixed',
      ltv: 80,
      dti: 38,
      incomeDocType: 'full_doc',
    },
    status: 'submitted',
    stage: 'processing',
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2024-02-05T14:30:00Z',
    submittedAt: '2024-02-02T09:00:00Z',
    assignedTo: 'lender-1',
  },
  {
    id: 'loan-2',
    brokerId: 'broker-1',
    brokerName: 'Premier Mortgage Group',
    borrower: {
      firstName: 'Jennifer',
      lastName: 'Martinez',
      email: 'jennifer.m@email.com',
      phone: '555-5678',
      dateOfBirth: '1990-07-22',
      creditScore: 680,
      isSelfEmployed: true,
      annualIncome: 95000,
    },
    property: {
      address: '789 Maple Drive',
      city: 'Oakland',
      state: 'CA',
      zipCode: '94612',
      propertyType: 'condo',
      occupancy: 'investment',
      propertyValue: 550000,
      yearBuilt: 2018,
      units: 1,
    },
    loanDetails: {
      purpose: 'purchase',
      loanAmount: 440000,
      loanTerm: 30,
      amortization: 30,
      interestRate: 7.25,
      paymentType: 'fixed',
      ltv: 80,
      incomeDocType: 'dscr',
      dscrRatio: 1.25,
      monthlyRent: 3500,
      monthlyExpenses: 2800,
    },
    status: 'in_review',
    stage: 'underwriting',
    createdAt: '2024-01-25T11:00:00Z',
    updatedAt: '2024-02-06T16:45:00Z',
    submittedAt: '2024-01-26T10:00:00Z',
    assignedTo: 'lender-1',
  },
  {
    id: 'loan-3',
    brokerId: 'broker-1',
    brokerName: 'Premier Mortgage Group',
    borrower: {
      firstName: 'David',
      lastName: 'Chen',
      email: 'david.chen@email.com',
      phone: '555-9012',
      dateOfBirth: '1982-11-08',
      creditScore: 760,
      employerName: 'Medical Center',
      jobTitle: 'Physician',
      yearsEmployed: 8,
      isSelfEmployed: false,
      annualIncome: 285000,
    },
    property: {
      address: '321 Pine Street',
      city: 'Palo Alto',
      state: 'CA',
      zipCode: '94301',
      propertyType: 'sfr',
      occupancy: 'primary',
      propertyValue: 2100000,
      yearBuilt: 2020,
      units: 1,
    },
    loanDetails: {
      purpose: 'purchase',
      loanAmount: 1680000,
      loanTerm: 30,
      amortization: 30,
      interestRate: 6.5,
      paymentType: 'fixed',
      ltv: 80,
      dti: 32,
      incomeDocType: 'full_doc',
    },
    status: 'approved',
    stage: 'clear_to_close',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-02-07T11:20:00Z',
    submittedAt: '2024-01-16T08:00:00Z',
    closingDate: '2024-02-20',
    assignedTo: 'lender-1',
  },
  {
    id: 'loan-4',
    brokerId: 'broker-1',
    brokerName: 'Premier Mortgage Group',
    borrower: {
      firstName: 'Emily',
      lastName: 'Wilson',
      email: 'emily.w@email.com',
      phone: '555-3456',
      dateOfBirth: '1988-05-30',
      isSelfEmployed: false,
    },
    property: {
      address: '654 Birch Lane',
      city: 'Fremont',
      state: 'CA',
      zipCode: '94538',
      propertyType: 'townhouse',
      occupancy: 'primary',
      propertyValue: 720000,
    },
    loanDetails: {
      purpose: 'refinance',
      loanAmount: 500000,
      loanTerm: 30,
      amortization: 30,
      paymentType: 'fixed',
      ltv: 69.4,
      incomeDocType: 'full_doc',
    },
    status: 'draft',
    stage: 'lead',
    createdAt: '2024-02-08T14:00:00Z',
    updatedAt: '2024-02-08T14:00:00Z',
  },
];

// Mock Documents
export const mockDocuments: LoanDocument[] = [
  {
    id: 'doc-1',
    loanId: 'loan-1',
    name: 'Pay Stub - January 2024',
    category: 'income',
    status: 'approved',
    fileUrl: '/mock/paystub-jan-2024.pdf',
    fileSize: 245000,
    mimeType: 'application/pdf',
    uploadedAt: '2024-02-02T10:30:00Z',
    uploadedBy: 'broker-1',
    reviewedAt: '2024-02-03T11:00:00Z',
    reviewedBy: 'lender-1',
  },
  {
    id: 'doc-2',
    loanId: 'loan-1',
    name: 'W2 - 2023',
    category: 'income',
    status: 'approved',
    fileUrl: '/mock/w2-2023.pdf',
    fileSize: 180000,
    mimeType: 'application/pdf',
    uploadedAt: '2024-02-02T10:32:00Z',
    uploadedBy: 'broker-1',
    reviewedAt: '2024-02-03T11:05:00Z',
    reviewedBy: 'lender-1',
  },
  {
    id: 'doc-3',
    loanId: 'loan-1',
    name: 'Bank Statement - December',
    category: 'asset',
    status: 'pending',
    fileUrl: '/mock/bank-statement-dec.pdf',
    fileSize: 320000,
    mimeType: 'application/pdf',
    uploadedAt: '2024-02-05T09:15:00Z',
    uploadedBy: 'broker-1',
  },
];

// Mock Conditions
export const mockConditions: LoanCondition[] = [
  {
    id: 'cond-1',
    loanId: 'loan-1',
    title: 'Updated Proof of Employment',
    description: 'Please provide an updated employment verification letter dated within the last 30 days.',
    category: 'income',
    status: 'open',
    priority: 'high',
    dueDate: '2024-02-15',
    createdAt: '2024-02-05T14:00:00Z',
    createdBy: 'lender-1',
  },
  {
    id: 'cond-2',
    loanId: 'loan-1',
    title: 'Additional Bank Statements',
    description: 'Provide the last 2 months of bank statements for all accounts.',
    category: 'asset',
    status: 'pending',
    priority: 'medium',
    dueDate: '2024-02-12',
    createdAt: '2024-02-04T10:30:00Z',
    createdBy: 'lender-1',
  },
];

// Mock Audit Log
export const mockAuditLog: AuditLogEntry[] = [
  {
    id: 'audit-1',
    loanId: 'loan-1',
    action: 'created',
    performedBy: 'broker-1',
    performedByName: 'John Smith',
    timestamp: '2024-02-01T10:00:00Z',
  },
  {
    id: 'audit-2',
    loanId: 'loan-1',
    action: 'stage_changed',
    performedBy: 'lender-1',
    performedByName: 'Sarah Johnson',
    timestamp: '2024-02-03T14:30:00Z',
    previousValue: 'application',
    newValue: 'processing',
  },
  {
    id: 'audit-3',
    loanId: 'loan-1',
    action: 'document_uploaded',
    performedBy: 'broker-1',
    performedByName: 'John Smith',
    timestamp: '2024-02-05T09:15:00Z',
    notes: 'Bank Statement - December',
  },
];

// Mock Messages
export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    loanId: 'loan-1',
    senderId: 'lender-1',
    senderName: 'Sarah Johnson',
    senderRole: 'lender',
    message: 'Hi John, we need updated employment verification for this file. Can you reach out to the borrower?',
    createdAt: '2024-02-05T14:00:00Z',
    read: true,
  },
  {
    id: 'msg-2',
    loanId: 'loan-1',
    senderId: 'broker-1',
    senderName: 'John Smith',
    senderRole: 'broker',
    message: 'Sure, I\'ll contact them today and have it uploaded by tomorrow.',
    createdAt: '2024-02-05T14:15:00Z',
    read: true,
  },
  {
    id: 'msg-3',
    loanId: 'loan-1',
    senderId: 'lender-1',
    senderName: 'Sarah Johnson',
    senderRole: 'lender',
    message: 'Perfect, thanks!',
    createdAt: '2024-02-05T14:20:00Z',
    read: true,
  },
];
